### ISSUE TITLE
[options-and-settings-pages] Does not save the settings!

### ISSUE THREAD

**Issue by glaubersilva** [WebDevStudios/CMB2-Snippet-Library#29]
Before start, I need to say that I'm a beginner and my english not so good, but I'll try explain my problem...

I downloaded the snippet that generate a options page and add it on my plugin. After that, I can see and manipulate the menu and the fields of the new options page, but when I click in the save button the page refresh and everything go back to default settings.

https://github.com/WebDevStudios/CMB2-Snippet-Library/tree/master/options-and-settings-pages

I spend a lot of time trying to do this works, but no success! So I Downloaded the "CMB2-Example-Theme" to install and see how it works, but the theme have the same problem on "example options" page... 

https://github.com/WebDevStudios/CMB2-Example-Theme

Can someone help me?

Grateful right now and sorry for my bad English! ;-)

**Comment by andrew-ok7** [comment]
I am having a similar issue, it no longer works!
@glaubersilva look at older versions of cmb2 from 6 months ago, the option page example works from back then.

**Comment by jtsternberg** [comment]
Are you using the latest version (2.2.1) of CMB2 (or the master branch)?

I am using the latest version, pasted the file in my theme exactly as it's posted, and it works exactly as it should.

**Comment by andrew-ok7** [comment]
I am using 2.2.1

**Comment by jtsternberg** [comment]
@andrew-ok7 Please remove the code from your theme that you pasted here: https://github.com/WebDevStudios/CMB2/issues/609#issuecomment-198088742

The fields should be managed here: https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php#L124-L140

**Comment by andrew-ok7** [comment]
ok, I copied the whole class from there and added it to my functions file and it is working, thank you.
If I wanted 2 option pages (say, one for home page options and one for general site options) could I just duplicate the class, rename it "Myprefix_AdminHome" and replace "myprefix" with "myprefixhome" everywhere throughout the class?

**Comment by andrew-ok7** [comment]
Nevermind, I did that and it worked, I now have 2 different option pages in the dashboard, thank you very much @jtsternberg cmb2 is fantastic.

**Comment by glaubersilva** [comment]
Beginner problem! There were a "exit;" on my php (in submit button) code that was blocking the save method. Now, everything works like a charm...

Thanks everyone and let me enjoy to say that CMB2 it's really amazing! =D
