### ISSUE TITLE
'object_types' not being respected

### ISSUE THREAD

**Issue by timothyjensen** [WebDevStudios/CMB2-Snippet-Library#37]
@jtsternberg I am attempting to display fields below the title on Pages only using this example: https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/misc/outputting-forms-outside-metaboxes.php.  Unfortunately the fields display below the title on all post types. Is there a fix to display them conditionally?

**Comment by jtsternberg** [comment]
Try that updated snippet.

**Comment by timothyjensen** [comment]
Perfect!  Thanks, Justin.

**Comment by jtsternberg** [comment]
👍
