### ISSUE TITLE
Improve field style like metabox for admin page

### ISSUE THREAD

**Issue by Mte90** [WebDevStudios/CMB2-Snippet-Library#46]
As screenshot
![schermata 2016-10-06 alle 12 42 47-fullpage](https://cloud.githubusercontent.com/assets/403283/19149505/aecc9196-8bb1-11e6-9d71-edde2c119928.png)
I have a pure css code of 25 lines that convert the style of the cmb fields in the settings page in that way, what is the best section in this repo for this type of stuff?

**Comment by jtsternberg** [comment]
This is for options/settings pages? maybe in here: https://github.com/WebDevStudios/CMB2-Snippet-Library/tree/master/options-and-settings-pages

**Comment by Mte90** [comment]
pr done :-)
