### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by jajouka79** [WebDevStudios/CMB2-Snippet-Library#5]
hi, thanks for this addition, i moved from cmb1 to cmb2 and some of my custom fields stopped working. hopefully this library will help. coul you please tell me how/ where i install it, and does it need initialising? thanks

**Comment by jtsternberg** [comment]
You wouldn't want to install this library. It's simply a resource of snippets that you can use to help work with and modify CMB2. If you have support issues, your best bet is to take them to the [CMB2 support forum](https://wordpress.org/support/plugin/cmb2).

**Comment by jajouka79** [comment]
ok, thanks very much for letting me know
