### ISSUE TITLE
cmb2_save_options-page_fields hook missing from theme options snippet

### ISSUE THREAD

**Issue by SteveHoneyNZ** [WebDevStudios/CMB2-Snippet-Library#50]
There's an old PR #23 that adds the hook but missing again now?

**Comment by jtsternberg** [comment]
It's [still there](https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php#L111).

**Comment by SteveHoneyNZ** [comment]
Ah being an idiot - a search replace I did had changed the hook so wasn't working, when searched found it in the hooks() originally made an assumption ;) Keep up the good work, cheers
