### ISSUE TITLE
Upon Plugin Activation Save Default Settings

### ISSUE THREAD

**Issue by DevinWalker** [WebDevStudios/CMB2-Snippet-Library#6]
We are using CMB2 to create a tabbed plugin admin panel. When a new user installs and activates the plugin they have to manually save the options before they are stored in the database. Do you know of a quick way to save default values so they are immediately available post installation?

**Comment by DevinWalker** [comment]
LMK if this issue is more appropriate in CMB2 core

**Comment by dustyf** [comment]
You should be able to use the register_activation_hook function (http://codex.wordpress.org/Function_Reference/register_activation_hook) to perform actions on the activation of your plugin.  Run update_option here and save values under the meta keys you use for your fields and they will be available once the plugin is activated.

**Comment by DevinWalker** [comment]
I figured as much, the issue though is how to exactly do this... I'm guessing two foreach loops like so:

```
// Populate some default values
	$give_settings = new Give_Plugin_Settings();
	foreach ( $give_settings->give_settings( null ) as $tab => $settings ) {

		foreach ( $settings as $option ) {

			if ( isset( $option['default'] ) ) {

				$options[ $option['id'] ] = $option['default'];
			}

		}

	}

	update_option( 'give_settings', array_merge( $give_options, $options ) );

```

I'm having trouble getting to work though...

**Comment by jtsternberg** [comment]
This question is quite a bit out of scope for this project. Also, your example assumes we know what `Give_Plugin_Settings` is, what `give_settings` outputs, where `$give_options` is coming from and what hook this is happening on.

**Comment by DevinWalker** [comment]
I agree it's a bit of a strange issue and I haven't provided too much context. Let me poke around a bit more on this...
